### ISSUE TITLE
What terminal theme are you using?

### ISSUE THREAD

**Issue by nloomans** [christopherwk210/html-primer#1]
Sorry for creating an issue for this, but I just need to know!

**Comment by christopherwk210** [comment]
@nloomans I'm using [iTerm 2](https://www.iterm2.com/) with [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh), [powerline](https://github.com/powerline/powerline), and [powerlevel9k](https://github.com/bhilburn/powerlevel9k). I made the theme myself by changing up the colors in iTerm 2 and customizing powerline/powerlevel9k in my `~/.zshrc`. The font I use is [Meslo](https://github.com/ryanoasis/nerd-fonts/releases/download/v1.0.0/Meslo.zip) LG S Regular for Powerline from [Nerd Font](https://nerdfonts.com/).
